version: "3"
services:
 scconfig:
    # Spring-Cloud服务配置项目
    image: springio/vcool-spring-cloud-config-boot2
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    ports:
      - "8088:8088"
    networks:
      - webnet
  visualizer:
    image: dockersamples/visualizer:stable
    ports:
      - "4001:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    deploy:
      placement:
        constraints: [node.role == manager]
    networks:
      - webnet
networks:
  webnet:
